[2024-04-08T14:38:32.121+0000] {scheduler_job_runner.py:780} ERROR - Executor reports task instance <TaskInstance: cassandra_sensor_dag.cassandra_sensor scheduled__2024-04-04T00:45:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
